services:
  airflow-webserver:
    image: apache/airflow:2.8.2
    restart: always
    depends_on:
      - airflow-scheduler
      - airflow-worker
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:123456@172.21.0.1:5432/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://172.21.0.1:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://postgres:123456@172.21.0.1:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: ZjBVJ0BLU1dUUTRiMWpOSA==
      AIRFLOW__WEBSERVER__SECRET_KEY: yoursecretkey
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.8.2
    restart: always
    depends_on:
      - airflow-worker
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:123456@172.21.0.1:5432/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://172.21.0.1:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://postgres:123456@172.21.0.1:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: ZjBVJ0BLU1dUUTRiMWpOSA==
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: scheduler

  airflow-worker:
    image: apache/airflow:2.8.2
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:123456@172.21.0.1:5432/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://172.21.0.1:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://postgres:123456@172.21.0.1:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: ZjBVJ0BLU1dUUTRiMWpOSA==
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: celery

  airflow-init:
    image: apache/airflow:2.8.2
    depends_on:
      - airflow-worker
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:123456@172.21.0.1:5432/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://172.21.0.1:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://postgres:123456@172.21.0.1:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: ZjBVJ0BLU1dUUTRiMWpOSA==
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: bash -c "airflow db migrate && airflow users create --username admin --firstname admin --lastname admin --role Admin --email admin@example.com --password admin"

